name: untitled
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  page_transition: ^2.0.4
  http: 0.13.3
  flutter:
    sdk: flutter
  path_provider: ^2.0.6
  path:
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.0.8
  shared_preferences:
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.2
  cloud_firestore:
  firebase_core:

assets:
  - assets/images

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true